spring.application.name=ParishayHealthHub
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/parishay_health_hub
spring.datasource.username=root
spring.datasource.password=Rai143Tassima@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect